"""Mem0-backed replacement for ``LocalMemoryStore``: raw fact storage really
goes through ``mem0.Memory`` now (real dependency, real embedding+vector
search), matching the paper's claim that entity nodes point to "underlying
Mem0 backend raw memory entry indices." supermem's own cognitive_graph/
rightbrain graph layers are unchanged -- they just reference the memory_id
values mem0 hands back, instead of ids generated by ``format_memory_id()``.

Two deliberate divergences from a naive "just call mem0" integration,
verified against the actually-installed ``mem0ai`` (real source read, not
assumed from docs):

1. ``add(infer=True)`` is NOT used, and supermem's own ADD/UPDATE/DELETE/NONE
   conflict resolver (``extract_facts_openai.ConflictResolver``) is kept as
   the decision-maker, not retired. Read ``mem0/memory/main.py``'s
   ``_add_to_vector_store`` directly: in this installed version, the
   ``infer=True`` path only does exact hash-based dedup against existing
   memories -- every extracted fact that isn't a byte-identical duplicate
   comes back with ``event: "ADD"``, there is no real semantic UPDATE/DELETE
   branch in this code path. That's weaker than what supermem already had
   (an LLM decides ADD vs UPDATE vs DELETE vs NONE per fact, aligned with
   mem0's own official prompt). So this store uses ``add(infer=False)``,
   which just stores exactly the text it's given -- supermem's own extractor
   and conflict resolver still do the actual decision-making upstream, mem0
   is purely "store this fact, give me back an id and a real embedding."

2. ``add_records_with_ids()`` IGNORES the caller-supplied ids. mem0's public
   ``add()`` has no id= parameter -- it always mints its own UUID. The one
   caller of this method (``LeftBrainMemoryRepository.append_extracted``)
   already treats this method's *return value* as the authoritative id list
   (zips it against ``annotated_facts`` for cognitive-graph linking), so this
   is safe: callers just start seeing mem0's ids instead of supermem's own
   ``format_memory_id()`` ids. This is the actual mechanism by which "the
   graph layer now references mem0 ids" happens.

The lexical/time-question reranking bonus (``_lexical_time_bonus`` et al.,
tuned against real accuracy runs) is NOT something mem0 provides -- it's
re-applied here on top of whatever candidates mem0's own cosine search
returns, so migrating storage backends doesn't quietly regress that tuning.

Concurrency note (real regression found + fixed): the old ``LocalMemoryStore``
was hand-rolled SQLite in WAL mode, which natively supports many concurrent
readers. mem0's local/embedded Qdrant mode does NOT -- a second
``mem0.Memory`` client pointed at the same on-disk path raises "Storage
folder ... is already accessed by another instance of Qdrant client" the
moment it's constructed, and it's not a transient error: every subsequent
call on the FIRST client also starts failing. Real repro: a 16-worker
``ThreadPoolExecutor`` QA eval that constructs a fresh ``SuperMem`` per
question (same ``memory_root``, common pattern -- e.g. this exact codebase's
own ``research/eval_locomo_baseline_supermem.py``) failed 137/152 questions
this way, not occasionally -- essentially every question after the first
thread grabbed the lock. Fixed by caching one ``Memory`` client per resolved
``memory_root`` path (``_MEM0_CLIENT_CACHE`` below) -- this makes concurrent
``SuperMem`` construction against the same path safe *within one process*
(all threads share the one real connection). It does NOT make it safe
*across processes* -- two separate Python processes pointed at the same
memory_root will still collide, because Qdrant's local mode fundamentally
has no multi-process story (its own error message says so: "use Qdrant
server instead"). Real deployments that need multi-process access to the
same memory_root need an actual Qdrant server, not local/embedded mode --
out of scope for this fix, called out here so it isn't rediscovered the
expensive way again.
"""

from __future__ import annotations

import os
import threading
from pathlib import Path
from typing import Any, Sequence

# mem0 sends posthog telemetry synchronously on every operation (a feature-flags network
# round trip). In testing this blew up the vector retrieval step of each Search, rank_ms,
# from ~8ms to ~280ms (97% of the whole Search). Off by default -- users who want it can
# set MEM0_TELEMETRY=1 to override. Must come before any mem0 import (mem0's Memory is
# only imported inside the methods below, so this line at module top is always first).
os.environ.setdefault("MEM0_TELEMETRY", "False")

from supermem.leftbrain.local_memory_store import (
    MemorySearchHit,
    TextEmbedder,
    _DATE_Q_RE,
    _DATE_RE,
    _DURATION_Q_RE,
    _DURATION_RE,
    _content_words,
    _lexical_time_bonus,
    date_overlap_bonus,
    query_dates,
)
from supermem.llm_config import resolve_model


def _as_date(v) -> str:
    """Take YYYY-MM-DD; return "" if it isn't a date (a time of day, None, or garbage all count as not)."""
    s = str(v or "")[:10]
    return s if len(s) == 10 and s[:4].isdigit() and s[4] == "-" else ""


def _resolve_chat_model() -> str:
    return resolve_model()


class _Mem0EmbedderAdapter:
    """Wraps any ``TextEmbedder`` as a real ``mem0.embeddings.base.EmbeddingBase``
    so ``mem0.Memory`` actually uses it, instead of always building its own
    internal OpenAI embedder regardless of what's passed to this store's
    constructor (previously the ``embedder`` argument was read only for
    ``.model_name``/``.dimensions`` -- see this file's git history / the
    comment that used to sit where this class now does).

    Not wired in through mem0's config-driven ``EmbedderFactory`` (its
    ``provider="langchain"`` option always calls the wrapped model's
    ``embed_query``, even when mem0 itself is embedding text to *store* --
    confirmed by reading ``mem0/embeddings/langchain.py``, not assumed).
    Instead, ``Memory.__init__`` builds a throwaway placeholder embedder from
    ``config.embedder`` and stores it on the plain public attribute
    ``self.embedding_model`` -- swapping that attribute right after
    construction (see below) is the real, correct hook: ``Memory.add()``/
    ``.search()`` call ``self.embedding_model.embed(text, "add"|"search")``
    directly, with the actual action, letting this adapter route add vs.
    search to different text (E5-family local models need a "query: "/
    "passage: " prefix distinction to hit their real accuracy -- see
    local_embedder.py in openai_voice_demo for the concrete case). An
    embedder opts into that by exposing ``embed_query_text(text) ->
    list[float]``; without it, both actions fall back to ``embed_texts()``
    (right for the default OpenAI embedder, which treats query and document
    text identically).
    """

    def __init__(self, embedder: TextEmbedder) -> None:
        self._embedder = embedder

    def embed(self, text: str, memory_action: str | None = None) -> list[float]:
        if memory_action == "search":
            query_fn = getattr(self._embedder, "embed_query_text", None)
            if query_fn is not None:
                return query_fn(text)
        return self._embedder.embed_texts([text])[0]

    def embed_batch(self, texts: list[str], memory_action: str = "add") -> list[list[float]]:
        if memory_action == "search":
            query_fn = getattr(self._embedder, "embed_query_text", None)
            if query_fn is not None:
                return [query_fn(t) for t in texts]
        return self._embedder.embed_texts(list(texts))


# The local/embedded qdrant storage for a given memory_root can only be held by one
# mem0.Memory client connection -- completely different from the LocalMemoryStore era
# (hand-rolled SQLite, WAL mode natively supports many concurrent readers), and a real
# reproduced problem: whenever a caller creates its own SuperMem per thread/process against
# the same memory_root (e.g. a thread pool running QA concurrently, a new SuperMem instance
# per call), as soon as the second connection is made, every later operation on the first
# one fails with "Storage folder ... is already accessed by another instance of Qdrant
# client" -- not occasionally, every time (real repro: a LoCoMo eval of 152 questions with
# 16 worker threads had 137 questions fail outright from this; only 15 happened to grab the lock).
# Cache the built Memory client keyed by (absolute path of qdrant_path); any later
# Mem0BackendStore construction pointing at the same memory_root reuses that connection
# instead of fighting for the lock -- one real connection per real storage directory,
# naturally safe across threads within a process.
_MEM0_CLIENT_CACHE: dict[str, Any] = {}
_MEM0_CLIENT_CACHE_LOCK = threading.Lock()


#: mem0 emits warnings when some optional dependencies aren't installed, but it runs fine
#: without them (spaCy only affects lemmatization, fastembed only the BM25 path). A first-time
#: user seeing three red lines around the results would think the run failed. Installed means
#: no warning; not installed shouldn't be alarming either -- silence these by exact logger name.
def _quiet_optional_deps() -> None:
    import logging
    import os
    if os.environ.get("SUPERMEM_VERBOSE", "0") != "0":
        return
    # mem0's optional-dependency warnings (runs fine without them) + an "Updating memory
    # with data=..." line for every stored item; the openai SDK logs "HTTP Request: POST ... 200 OK"
    # per request. These are all library INFO-level noise; one basic run can print dozens of
    # lines and bury the real results.
    for name in ("mem0", "openai", "httpx", "httpcore"):
        logging.getLogger(name).setLevel(logging.WARNING)
    for name in ("mem0.utils.spacy_models", "mem0.vector_stores.qdrant", "mem0.memory.main"):
        logging.getLogger(name).setLevel(logging.ERROR)


#: qdrant-client's __del__ trips over an already-cleared sys.meta_path at interpreter exit
#: and throws an ImportError traceback -- the results were printed long before, it's purely
#: alarming. Closing proactively before process exit avoids reaching that broken __del__.
def _close_on_exit(mem0_instance) -> None:
    import atexit

    def _close():
        try:
            mem0_instance.vector_store.client.close()
        except Exception:
            pass

    atexit.register(_close)


def evict_client(memory_root) -> None:
    """Drop this space's cached mem0 client and close it (Qdrant lock + history sqlite).

    Call before deleting a space's files. The cache outlives the space, so without this a
    space re-created under the same name reuses the old client: it serves the deleted
    vectors from RAM and fails every write with "attempt to write a readonly database".
    """
    key = str((Path(memory_root) / "vectors").resolve())   # same key as __init__ builds
    with _MEM0_CLIENT_CACHE_LOCK:
        client = _MEM0_CLIENT_CACHE.pop(key, None)
    if client is None:
        return
    for close in (lambda: client.vector_store.client.close(), getattr(client, "close", None)):
        if close is None:
            continue
        try:
            close()
        except Exception:
            pass


class Mem0BackendStore:
    """Drop-in replacement for ``LocalMemoryStore`` backed by real ``mem0.Memory``.

    Implements the same method surface ``LeftBrainMemoryRepository`` calls on
    ``self._vector_store`` (see ``memory_repository.py``): ``search``,
    ``update_memory``, ``delete_memory``, ``add_records_with_ids``,
    ``list_ids``, ``existing_for_extractor``, ``memory_ids_with_time_expr``.
    """

    def __init__(self, embedder: TextEmbedder, *, memory_root: Path) -> None:
        self._embedder = embedder  # the real embedder used for add()/search() -- see _Mem0EmbedderAdapter below
        self._path = Path(memory_root)  # for parity with LocalMemoryStore._path (used by dev scripts)

        from supermem.utils.common import space as _space
        # If the embedding changed but points at the same space, say so clearly here instead
        # of waiting for qdrant to throw "shapes (n,384) and (1536,) not aligned"
        _space.check_dims(memory_root, embedder.dimensions)
        _space.describe(memory_root, dims=embedder.dimensions)
        qdrant_path = _space.vectors(memory_root)
        qdrant_path.mkdir(parents=True, exist_ok=True)
        cache_key = str(qdrant_path.resolve())

        with _MEM0_CLIENT_CACHE_LOCK:
            cached = _MEM0_CLIENT_CACHE.get(cache_key)
            if cached is not None:
                self._mem0 = cached
                return

            _quiet_optional_deps()

            from mem0 import Memory
            from mem0.configs.base import MemoryConfig
            from mem0.embeddings.configs import EmbedderConfig
            from mem0.llms.configs import LlmConfig
            from mem0.vector_stores.configs import VectorStoreConfig

            history_db = _space.db(memory_root)
            config = MemoryConfig(
                vector_store=VectorStoreConfig(provider="qdrant", config={
                    "collection_name": "supermem",
                    "embedding_model_dims": embedder.dimensions,
                    "path": str(qdrant_path),  # local/embedded qdrant, no server -- same as mem0's own default, just isolated per memory_root instead of a shared /tmp path
                }),
                # Throwaway placeholder -- constructing an OpenAIEmbedding here
                # is cheap (no network call until an actual .embed() happens,
                # see mem0/embeddings/openai.py) and MemoryConfig requires
                # *some* valid embedder provider to build at all. The real
                # embedder gets swapped in right below; this one is never used.
                embedder=EmbedderConfig(provider="openai", config={}),
                llm=LlmConfig(provider="openai", config={"model": _resolve_chat_model()}),
                history_db_path=str(history_db),
            )
            self._mem0 = Memory(config)
            _close_on_exit(self._mem0)
            # The real hook: Memory.add()/.search() call
            # self.embedding_model.embed(text, "add"|"search") directly (see
            # _Mem0EmbedderAdapter's docstring for why this, not mem0's
            # config-driven EmbedderFactory, is the correct place to plug in
            # embedder -- whatever TextEmbedder SuperMem was constructed
            # with, not always OpenAI's).
            self._mem0.embedding_model = _Mem0EmbedderAdapter(embedder)
            _MEM0_CLIENT_CACHE[cache_key] = self._mem0

    # ── write ────────────────────────────────────────────────────────────────

    def add_records_with_ids(
        self,
        user_id: str,
        items: Sequence[tuple[str, str, str, dict[str, Any]]],
    ) -> list[str]:
        """``items`` is ``(id, text, attributed_to, metadata)`` -- the ``id``
        component is ignored (see module docstring); returns the real ids
        mem0 generated, in the same order as ``items``.
        """
        ids: list[str] = []
        for _ignored_id, text, attributed_to, metadata in items:
            t = (text or "").strip()
            if not t:
                continue
            role = "assistant" if attributed_to == "assistant" else "user"
            result = self._mem0.add(
                messages=[{"role": role, "content": t}],
                user_id=user_id,
                infer=False,
                metadata=dict(metadata or {}),
            )
            entries = result.get("results") if isinstance(result, dict) else result
            if entries:
                ids.append(str(entries[0]["id"]))
        return ids

    def add_text(self, user_id: str, text: str, *, attributed_to: str = "user",
                 metadata: dict[str, Any] | None = None) -> str:
        ids = self.add_records_with_ids(user_id, [("", text, attributed_to, metadata or {})])
        if not ids:
            raise ValueError("text must not be empty")
        return ids[0]

    def update_memory(self, memory_id: str, new_text: str,
                       session_id: int | str | None = None,
                       observed_at: str | None = None) -> bool:
        t = new_text.strip()
        if not t:
            return False
        meta: dict[str, Any] = {}
        if session_id is not None:
            meta["session_id"] = session_id
        if observed_at is not None:
            meta["created_at"] = observed_at
        try:
            self._mem0.update(memory_id, text=t, metadata=meta or None)
            return True
        except Exception:
            return False

    def delete_memory(self, memory_id: str) -> bool:
        try:
            self._mem0.delete(memory_id)
            return True
        except Exception:
            return False

    def archive_memory(self, memory_id: str) -> bool:
        """Archive: set expiration_date to yesterday; mem0's own search()/get_all()
        already hide expired memories automatically by this field (actually read
        _payload_is_expired in mem0.memory.main.py, not assumed) -- directly reuse this
        real existing mechanism rather than building a separate "archived" flag in
        supermem's own graph layer.
        """
        from datetime import date, timedelta
        yesterday = (date.today() - timedelta(days=1)).isoformat()
        try:
            self._mem0.update(memory_id, expiration_date=yesterday)
            return True
        except Exception:
            return False

    def unarchive_memory(self, memory_id: str) -> bool:
        """Undo archiving: clear expiration_date (expiration_date=None in mem0 update()
        clears it, see its docstring)."""
        try:
            self._mem0.update(memory_id, expiration_date=None)
            return True
        except Exception:
            return False

    # ── read ────────────────────────────────────────────────────────────────

    def list_ids(self, *, user_id: str) -> list[str]:
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return [str(e["id"]) for e in entries]

    def list_entries(self, *, user_id: str) -> list[dict[str, str]]:
        """(id, text, date) for all memories -- date is metadata.time_start (ingest's observed_at),
        falling back to created_at. For batch jobs like schema description refresh; no vector search."""
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        out = []
        for e in entries:
            md = e.get("metadata") or {}
            # Include role too: the assistant's own utterances are stored as-is (see add_text's
            # attributed_to="assistant"), and callers need to be able to pick them out -- e.g. the
            # web demo's brain map should only show "memories about the user"; growing nodes from
            # the assistant's replies would be wrong.
            out.append({"id": str(e["id"]), "text": str(e.get("memory", "") or ""),
                        "date": str(md.get("time_start") or e.get("created_at") or "")[:10],
                        "role": str(md.get("role") or e.get("role") or "user")})
        return out

    def existing_for_extractor(self, user_id: str, *, limit: int = 50) -> list[dict[str, str]]:
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=limit)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return [{"id": str(e["id"]), "text": str(e.get("memory", ""))} for e in entries[:limit]]

    def memory_ids_with_time_expr(self, user_id: str, *, kind: str) -> set[str]:
        pat = _DURATION_RE if kind == "duration" else _DATE_RE
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return {str(e["id"]) for e in entries if pat.search(str(e.get("memory", "") or ""))}

    def search(
        self,
        query: str,
        *,
        user_id: str,
        top_k: int = 10,
        threshold: float | None = None,
        memory_id_filter: set[str] | list[str] | None = None,
        rescue_k: int = 0,
        include_assistant: bool = False,
    ) -> list[MemorySearchHit]:
        q = query.strip()
        if not q:
            return []

        # mem0's search() has no "restrict to this explicit id set" filter --
        # only metadata filters (user_id/agent_id/run_id). When the caller
        # narrows candidates first (SearchData()'s slot/entity narrowing),
        # fetch a wide-enough candidate set from mem0 and filter client-side,
        # same as before: narrowing doesn't happen at the mem0 query itself.
        fetch_k = 10_000 if memory_id_filter else max(top_k * 3, 20)
        # search() takes user_id via filters={}, NOT a direct user_id= kwarg
        # (unlike add(), which does accept user_id= directly) -- confirmed
        # from the real installed SDK's signature, not assumed by analogy.
        # The assistant's utterances are in the same store too (role=assistant) and are not
        # recalled by default -- asking "what am I allergic to" and getting back "the assistant
        # suggested you avoid nuts" means it cites itself, and answers drift further and further.
        # They are only included when the question itself asks "what did you say before"
        # (see asks_about_assistant).
        flt: dict[str, Any] = {"user_id": user_id}
        if not include_assistant:
            flt["role"] = {"ne": "assistant"}
        raw = self._mem0.search(q, filters=flt, top_k=fetch_k, threshold=0.0)
        entries = raw.get("results", []) if isinstance(raw, dict) else raw

        id_filter = set(memory_id_filter) if memory_id_filter else None
        q_words = _content_words(q)
        want_dur = bool(_DURATION_Q_RE.search(q))
        want_date = (not want_dur) and bool(_DATE_Q_RE.search(q))
        q_dates = query_dates(q)     # the days "next week" expanded to (see time_expand)

        hits: list[MemorySearchHit] = []
        for e in entries:
            mid = str(e["id"])
            if id_filter is not None and mid not in id_filter:
                continue
            cos = float(e.get("score") or 0.0)
            if threshold is not None and cos < threshold:
                continue
            text = str(e.get("memory", ""))
            bonus, time_hit = _lexical_time_bonus(q_words, want_dur, want_date, text)
            bonus += date_overlap_bonus(q_dates, text)
            metadata = {k: v for k, v in e.items()
                        if k not in ("id", "memory", "score", "hash", "user_id", "created_at", "updated_at")}
            # Event time: Ingest's observed_at is written into both metadata.time_start and the
            # top-level created_at; check both. Previously nothing was taken here -- created_at
            # was excluded by the line above, and time_start was nested in metadata, not
            # flattened, so the time was stored all the way into the DB yet never reached the
            # prompt; temporal questions relied entirely on dates that happened to appear in the fact text.
            inner = e.get("metadata") or {}
            # time_start often holds a **time of day** ("15:18:36") rather than a date. It used to
            # read `time_start or created_at` -- a time of day is truthy, `or` short-circuits, and
            # the fallback half never ran; then isdigit() rejected it, so observed_at was always "".
            # Two consequences: the time weight in retrieval ranking never took effect, and the
            # memory's [date] prefix never reached the prompt (while the persona says "if a memory
            # carries a date, use that date"). So first validate that it looks like a date.
            observed = _as_date(inner.get("time_start")) or _as_date(e.get("created_at"))
            hits.append(MemorySearchHit(
                memory_id=mid, text=text, score=cos + bonus,
                attributed_to=str(e.get("attributed_to") or "user"),
                metadata=metadata, base_score=cos, time_boost=time_hit,
                observed_at=observed,
            ))

        hits.sort(key=lambda h: h.base_score, reverse=True)
        base = hits[:top_k]
        if rescue_k <= 0:
            return base
        seen = {h.memory_id for h in base}
        boosted = sorted(
            (h for h in hits if h.time_boost and h.memory_id not in seen),
            key=lambda h: h.score, reverse=True,
        )
        return base + boosted[:rescue_k]
